language: node_js
node_js:
  - "8"
script:
  - echo ${TRAVIS_BRANCH}
  - echo $TRAVIS_BRANCH

  - git diff -z --diff-filter=AMCR --name-only HEAD^^ *.js | xargs -0 npm run lint --
  
  - cd .ci && ./checkDeletedTxt.sh
cache: npm
