language: node_js
node_js:
  - "8"
script:
  - git remote set-branches --add origin $TRAVIS_BRANCH
  - git fetch
  - git diff -z --diff-filter=AMCR --name-only origin/$TRAVIS_BRANCH *.js | xargs -0 npm run lint --
  - cd .ci && ./checkDeletedTxt.sh
cache: npm
