language: node_js
node_js:
  - "8"
script:
  - echo ${TRAVIS_BRANCH}
  - git remote -v
  - git branch -v
  
  - TRAVIS_FROM_BRANCH="travis_from_branch"
  - git branch $TRAVIS_FROM_BRANCH
  - git checkout $TRAVIS_FROM_BRANCH
       
  - git fetch --all 
  - git pull --all
  
  
  - git remote set-branches --add origin master
  
  - git remote -v
  - git branch -v
  
  - git fetch --all 
  
  - git remote -v
  - git branch -v
  - git diff origin/master # now works as normal
  
  - git pull --all
  
  - git remote -v
  - git branch -v
  
  - git diff origin/master # now works as normal
  
  - git fetch origin $TRAVIS_BRANCH
  - git checkout -qf FETCH_HEAD

  - git checkout $TRAVIS_BRANCH
       
  - git checkout $TRAVIS_FROM_BRANCH
    
  - git diff HEAD^^
  
  - git diff -z --diff-filter=AMCR --name-only HEAD^^ *.js
  
  - git show

  - git diff -z --diff-filter=AMCR --name-only HEAD^^ *.js | xargs -0 npm run lint --
  
  - cd .ci && ./checkDeletedTxt.sh
cache: npm
