language: node_js
node_js:
  - "8"
script:
  - echo ${TRAVIS_BRANCH}
  - echo TRAVIS_BRANCH
  
  
  - git remote set-branches --add origin ${TRAVIS_BRANCH}
  - git fetch
  - git diff -z --diff-filter=AMCR --name-only origin/${TRAVIS_BRANCH} *.js | xargs -0 npm run lint --
  
  
  - git remote set-branches --add origin ${TRAVIS_BRANCH}
  - git fetch
  - git diff -z --diff-filter=AMCR --name-only origin/master *.js | xargs -0 npm run lint --
  
  
  
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch
  - git diff -z --diff-filter=AMCR --name-only HEAD origin/${TRAVIS_BRANCH} *.js | xargs -0 npm run lint 
  
  
  - git remote set-branches --add origin eLibrary-eslint-warnings
  - git fetch
  - git diff origin/master # now works as normal
  
  
  
  - cd .ci && ./checkDeletedTxt.sh
cache: npm
