language: node_js
node_js:
  - "8"
script:
  - git checkout --detach
  - git fetch origin '+refs/heads/*:refs/heads/*'
  - git diff -z --diff-filter=AMCR --name-only $TRAVIS_COMMIT_RANGE *.js | xargs -0 npm run lint --
  - cd .ci && ./checkDeletedTxt.sh
cache: npm
